import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'CBD Parcel Services',
    rating: 5,
    ratingCount: 8,
    price: 70,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'CBD Errand Services',
    rating: 5,
    ratingCount: 15,
    price: 100,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Mtaani Parcel Services',
    rating: 4,
    ratingCount: 7,
    price: 120,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Mtaani Errand Services',
    rating: 4,
    ratingCount: 12,
    price: 150,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'CBD - Outside Nairobi County',
    rating: 4,
    ratingCount: 32,
    price: 240,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Mtaani - Outside Nairobi County',
    rating: 5,
    ratingCount: 14,
    price: 290,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'CBD to Mtaani(vice versa)',
    rating: 4,
    ratingCount: 6,
    price: 120,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Mtaani to Mtaani',
    rating: 4,
    ratingCount: 6,
    price: 200,
    category: 'Beginner',
  },
]
